[WIP] Add tracing support
projectriff-archive/http-gateway pull request #20
Opened 2017-12-18 22:06 UTC by freynca

- Refactoring
- Add zipkin tracing [https://github.com/projectriff/http-gateway/issues/1]

2017-12-18 22:06 UTC, pivotal-issuemaster commented
@freynca Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=projectriff/http-gateway&pullRequestId=20)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=projectriff/http-gateway&pullRequestId=20) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2018-01-04 14:08 UTC, ericbottard requested changes
It was hard to review this PR using the GH interface as it touches so many files. A couple of comments though:
- The first 3 commits are actually unrelated and should be part of a different PR. Some things are now exported when then don't deserve to IMO, but let's discuss on a dedicated PR
- the refactoring approach (see above) should go in the direction of making the http-gw an "object" (in the OO sense) to avoid passing so many additional parameters around.
- as to the actual zipkin stuff, I think it would benefit from being implemented as a decorator around a `http.HandlerFunc`

2018-01-04 14:08 UTC, ericbottard commented on pkg/handlers/message_handler.go
> +func MessageHandler(producer sarama.AsyncProducer, traceContext TraceContext) http.HandlerFunc {
This should be implemented using the Decorator pattern I think

2018-01-04 14:13 UTC, ericbottard commented
Also, this will need to be rebased on top of latest master. I'm not sure I understand why so many files were touched in `vendor/`?

2018-01-08 14:57 UTC, freynca commented
Closing; will rebase and submit new PRs as needed.

2018-01-08 14:57 UTC, closed without merging