Rework dockerization so that it uses multi-stage docker builds
projectriff-archive/http-gateway pull request #26
Opened 2018-01-23 16:57 UTC by ericbottard

2018-01-31 07:54 UTC, glyn approved these changes
Anything that shrinks the Makefile looks good to me.

2018-02-01 12:22 UTC, glyn requested changes
Beautiful! One question...

2018-02-01 12:22 UTC, glyn commented on Makefile
> +GO_SOURCES = $(shell find cmd -type f -name '*.go')
By excluding the Go files in `/pkg`, won't this mean that some targets will not be rebuilt when a `*.go` file in `/pkg` is modified?

2018-02-01 12:23 UTC, ericbottard commented on Makefile
> +GO_SOURCES = $(shell find cmd -type f -name '*.go')
There is no `pkg` at this time on master

2018-02-01 12:45 UTC, glyn commented on Makefile
> +GO_SOURCES = $(shell find cmd -type f -name '*.go')
Ah. Of course! Apologies.

2018-02-01 12:45 UTC, merged